config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get '/searchs/filter' => "searchs#filter"
  get "/searchs" => "searchs#index"
  post "/searchs/filter" => "searchs#filter", as: :search_filter

  resources :novelties, only: [:index] do
    collection do
      get 'betters'
    end
  end

  resources :centers do
    collection do
      get 'opinions'
      post "images"
      post "delete_images"
      get "admin"
      get "center_admin"
    end
    resources :reviews
  end

  resources :users
  resources :adverts

  resource :session, only: [:new, :create, :destroy]

  get '/logout' => "sessions#destroy", as: "logout"
  get '/notices/centers' => "notices#centers", as: "centers_info"
  get '/notices/trainners' => "notices#trainners", as: "trainners_info"

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  has_many :reviews
  has_many :adverts, :dependent => :delete_all
  has_many :centers, :dependent => :delete_all
  attr_accessor :password
  before_save :encrypt_new_password
  validates :name, presence: {message: "Introduzca su nombre"}, length: {within: 2..16, message: "El nombre debe tener al menos dos caracteres"}
  validates :email, uniqueness: {case_sensitive: false, message: "Ya existe un usuario registrado con esa direccion de correo"}, length: {in: 6..40, message: "Correo inválido"}, format: {with: /\A(\S+)@(.+)\.(\S+)\z/, message: "Introduzca una direccion de correo válida"}
  validates :password, confirmation: {message: "Las contraseñas no coindicen"}, length: {within: 8..20, message: "La contraseña debe tener una longitud mínima de 8 caracteres"}, presence: {if: :password_required?, message: "La contraseña no puede estar en blanco"}
  validates :password_confirmation, presence: {message: "Es necesario que confirme la contraseña"}
  validates :username, uniqueness: {case_sensitive: false, message: "El username está ocupado"}, length: {in: 4..20, message: "El nombre de usuario debe tener al menos cuatro caracteres"}
  validates :municipality, presence: true
  before_save :municipality_to_lower
  scope :where_municipality, -> (municipality = nil) { where("users.municipality = ?", municipality) }

  def self.authenticate(username, password)
    user = find_by_username(username)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end

  protected
  def encrypt_new_password
    return if password.blank?
    self.hashed_password = encrypt(password)
  end

  def password_required?
    hashed_password.blank? || password.present?
  end

  def encrypt(string)
    Digest::SHA1.hexdigest(string)
  end

  def municipality_to_lower
    self.municipality = self.municipality.downcase
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:edit, :update]

  def new
    if session[:username]
      flash[:alert] = "Debe cerrar la sesión en primer lugar"
      redirect_to root_url
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: 'Bienvenido a RateFit, en la esquina superior derecha puedes iniciar sesion clickando en el usuario'
    else
      render action: :new
    end
  end

  def edit
  end

  def index
    @users = User.where_municipality(params[:mun_user].downcase)
    if @users
      respond_to do |format|
        format.html
        format.js
      end
    else
      respond_to do |format|
        format.js { render "fail_search.js.erb" }
      end
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    if !@user
      redirect_to "/searchs", notice: "El usuario no existe" and return false
    elsif @user.adverts.count == 0
      redirect_to "/searchs", notice: "¡El usuario #{@user.name} no posee anuncios, ponte en contacto con él y animale a crear uno! Su email: #{@user.email}" and return false
    end
  end

  def update
    if @user.update(user_params)
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render "fail_update.js.erb" }
      end
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :name, :municipality)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_update_user.html.erb
<%= form_for(@user, remote: true, html: {class: 'col-xs-10 col-sm-4 col-sm-offset-1 col-md-offset-1 col-lg-offset-1', id: "user_update", role: "form"}) do |f| %>
    <a name="user_edit" title="user_edit"></a>
    <h5><strong>Editar perfil</strong></h5>
    <div class="field form-group">
      <%= f.label :email %></br>
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :password %></br>
      <%= f.password_field :password, class: "form-control", value: "#{@user.password}" %>
    </div>

    <div class="field form-group">
      <%= f.label :password_confirmation %></br>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="field form-group" class="col-xs-10 col-lg-4">
      <label for="municipality">Municipio</label>
      <select name="user[municipality]" class="form-control" id="municipality">
        <option>Las Palmas de Gran Canaria</option>
        <option>Tejeda</option>
        <option>Telde</option>
        <option>Gáldar</option>
      </select>
    </div>

    <div class="actions">
      <%= f.submit "Actualizar perfil", class: "btn btn-default" %>
      <br><br>
    </div>

<% end %>

app/views/users/_user.html.erb
<li>
  <%= div_for user do %>
      <h4>
        <%= link_to user.name, user %>
      </h4>
      <p><i class="fa fa-2x fa-envelope"></i><strong> Contacto con <%= user.name %>:</strong> <%= user.email %></p>
      <% if user.adverts.count == 0 %>
      <p class="alert alert-info", style="margin-right: 5px">
        <%= user.name %> aún no tiene anuncios. Ponte en contacto con él y anímense a hacer ejercicio.
      </p>
      <% end %>
  <% end %>
</li>

app/views/users/edit.html.erb
<div id="adverts" class="col-xs-11 col-sm-6 col-lg-6">

  <h3>Mis anuncios</h3>
  <ul>
    <%= render @user.adverts %>
  </ul>
  <% if @user.adverts.count == 0 %>
      <p>¡Añade tu primera reseña!</p>
  <% end %>
  <button class="btn btn-default" data-toggle="modal" data-target="#advert_modal">Añadir anuncio</button>
  <br/>
  <br/>
</div>
</div>

<div class="modal fade" id="advert_modal" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <a type="button" class="close" data-dismiss="modal">&times;</a>
        <h4 class="modal-title">Inicia sesión o regístrate gratis para escribir una reseña</h4>
      </div>
      <div class="modal-body">
        <%= form_tag adverts_path, remote: true do %>
            <div class="field form-group">
              <%= label_tag :title, 'Título' %></br>
              <%= text_field_tag :title, nil, class: 'form-control', required: true %>
            </div>
            <div class="field form-group">
              <%= label_tag :description, "Descripción" %></br>
              <%= text_area_tag :description, nil, class: 'form-control', required: true %>
            </div>
            <div class="actions">
              <%= submit_tag 'Añadir', class: 'btn btn-default' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "update_user" %>

<div class="modal fade" id="advert_info">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Se han encontrado los siguientes errores</h4>
      </div>
      <div class="modal-body">

      </div>
    </div>
  </div>
</div>

app/views/users/fail_update.js.erb
<% if @user.errors.any? %>
  <% @info = "" %>
  <% @user.errors.messages.values.each do |msg| %>
    <% msg.each do |m| %>
      <% @info +=  m + "\n" %>
    <% end %>
  <% end %>
<% end %>

$("#info .modal-body").html("<div class='alert alert-danger'><%= j @info %></div>");
$("#info").modal("show");

app/views/users/index.html.erb
<div class="col-xs-10 col-sm-6 col-lg-5" id="custom_user_search">
  <h4 class="" style="color: #ffa33f"><strong>Búsqueda de entrenadores</strong></h4>
  <%= form_tag users_path, method: :get, remote: true do %>
      <div id="municipality_user" class="col-xs-12 col-sm-10 col-lg-10">
        <label for="mun_user">Municipio</label>
        <select name="mun_user" class="form-control" id="mun_user">
          <option>Las Palmas de Gran Canaria</option>
          <option>Tejeda</option>
          <option>Telde</option>
          <option>Gáldar</option>
        </select>
        <br>
        <div class="actions col-xs-12">
          <%= submit_tag 'Buscar Entrenador', class: 'btn btn-default' %>
          <br><br>
        </div>
      </div>
  <% end %>
</div>

<div id="centers_result" class="col-xs-12 col-sm-5 col-lg-6">
  <h2 id="results_title" class="">Entrenadores</h2>
  <% if @users.count > 0 %>
      <ul>
        <%= render @users %>
      </ul>
  <% else %>
      <p id='fail_search'>
        <strong>No hemos encontrado entrenadores en este municipio</strong>
        <br>
        <br>
      </p>
  <% end %>
</div>

app/views/users/index.js.erb
$("#centers_result ul").html("<%= j render @users %>");
if ($("#centers_result ul").html() == "") {
  $("#centers_result ul").html("<li class='alert alert-warning'>No hemos encontrado entrenadores en este municipio.</li>");
}

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger col-xs-8 col-xs-offset-2 hidden-sm col-md-3 hidden-md hidden-lg">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <h4>No hemos podido crear su cuenta, es necesario que corrija los siguientes errores:</h4>
      <ul id="new_user_errors">
        <% @user.errors.messages.values.each do |msg| %>
            <% msg.each do |m| %>
                <li><%= m %></li>
            <% end %>
        <% end %>
      </ul>
    </div>
<% end %>

<div id="sign_up_form" class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4 col-lg-3 col-sm-offset-2">
  <%= form_for @user, url: users_path, html: {multipart: true} do |f| %>
      <h3>¡Regístrate gratis! <i class="fa fa-user"></i></h3>
      <div class="field form-group">
        <%= f.label :username, 'Nombre de usuario' %></br>
        <%= f.text_field :username, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= f.label :name, 'Nombre' %></br>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :email, 'Email' %></br>
        <%= f.text_field :email, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :password, 'Contraseña' %></br>
        <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :password_confirmation, 'Repita la contraseña' %></br>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <div class="field form-group" class="col-xs-10 col-lg-4">
        <label for="municipality">Municipio</label>
        <select name="user[municipality]" class="form-control" id="municipality">
          <option>Las Palmas de Gran Canaria</option>
          <option>Tejeda</option>
          <option>Telde</option>
          <option>Gáldar</option>
        </select>
      </div>

      <div class="actions">
        <%= f.submit 'Registrarse', :class => 'btn btn-default' %>
      </div>
      <br>

  <% end %>
</div>

<% if @user.errors.any? %>
    <div class="alert alert-danger hidden-xs col-xs-8 col-xs-offset-2 col-sm-3 col-lg-offset-2 col-lg-4">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <h4>No hemos podido crear su cuenta, es necesario que corrija los siguientes errores:</h4>
      <ul id="new_user_errors">
        <% @user.errors.messages.values.each do |msg| %>
            <% msg.each do |m| %>
                <li><%= m %></li>
            <% end %>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/show.html.erb
<h2 id="results_title" class="col-xs-10 col-xs-offset-1"><i class="fa fa-envelope"></i> Contacta con <%= @user.name %>:
</h2>
<h4 class="col-xs-10 col-xs-offset-1"><%= @user.email %></h4>
<div id="centers_result" class="col-xs-12 col-sm-10 col-md-8 col-md-offset-2 col-lg-offset-1 col-lg-5">
  <ul>
    <% @user.adverts.each do |advert| %>
        <li>
          <h3><%= advert.title %></h3>
          <p><%= advert.description %></p>
          <h6><%= advert.date %></h6>
        </li>
    <% end %>
  </ul>
  <br><br>
</div>

app/views/users/update.js.erb
$("#user_update input[type='password']").val("");
$("#user_email").val("<%= @user.email %>");
$("#info .modal-body").html("<div class='alert alert-success'>Su perfil ha sido actualizado</div>");
$("#info").modal("show");