config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get '/searchs/filter' => "searchs#filter"
  get "/searchs" => "searchs#index"
  post "/searchs/filter" => "searchs#filter", as: :search_filter

  resources :novelties, only: [:index] do
    collection do
      get 'betters'
    end
  end

  resources :centers do
    collection do
      get 'opinions'
      post "images"
      post "delete_images"
      get "admin"
      get "center_admin"
    end
    resources :reviews
  end

  resources :users
  resources :adverts

  resource :session, only: [:new, :create, :destroy]

  get '/logout' => "sessions#destroy", as: "logout"
  get '/notices/centers' => "notices#centers", as: "centers_info"
  get '/notices/trainners' => "notices#trainners", as: "trainners_info"

end

app/models/center.rb
class Center < ActiveRecord::Base
  validates_presence_of :tennis, :aerobic, :aquagym, :zumba, :fitness, :municipality
  before_save :municipalty_to_lower_case
  belongs_to :user
  has_many :reviews, :dependent => :delete_all
  has_many :center_images, :dependent => :destroy
  scope :filter, -> (filter = nil) { where("centers.name LIKE ?", "%#{filter}%") }
  scope :news, -> { order("created_at DESC").limit(5) }
  scope :betters, -> { order("rate DESC").limit(5) }
  scope :search_filter, -> (municipality, price = nil, stars = nil, aerobic = nil, fitness = nil, aquagym= nil, tennis= nil, zumba = nil) {
    where("centers.municipality = ? AND centers.price LIKE ? AND centers.rate >= ? AND centers.aerobic LIKE ? AND centers.fitness LIKE ? AND centers.aquagym LIKE ? AND centers.tennis LIKE ? AND centers.zumba LIKE ?",
          "#{municipality.downcase}", "%#{price}%", stars.to_f, "%#{aerobic}%", "%#{fitness}%", "%#{aquagym}%", "%#{tennis}%", "%#{zumba}%") }

  def get_images
    if images
      return images.split("&")
    else
      return []
    end
  end

  def municipalty_to_lower_case
    self.municipality = self.municipality.downcase
  end

  def get_media
    return (self.reviews.sum(:rate) / self.reviews.count)
  end
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  before_action :set_center, only: [:show]
  before_action :authenticate, only: [:destroy, :create]
  before_action :admin_authenticate, only: [:update, :edit, :images, :delete_images, :center_admin]

  def index
    @centers = Center.filter(params[:filter])
    if @centers.present?
      respond_to do |format|
        format.html
        format.js
      end
    else
      respond_to do |format|
        format.html
        format.js { render "fail_search.js.erb" }
      end
    end
  end

  def show
    redirect_to({action: :index}, notice: 'Centro no encontrado') unless @center
  end

  def set_center
    @center = Center.find_by_id(params[:id])
  end

  def opinions
    @center = Center.find_by_id(params[:id])
  end

  def new
    @center = Center.new
  end

  def edit
    if !Center.exists?(id: params[:id])
      redirect_to root_url, alert: "El centro no existe"
      return false
    end
    @center = Center.find(params[:id])
  end

  def update
    @center = Center.find(params[:id])
    if @center.update(center_params)
      redirect_to :back, notice: "Su centro deportivo se ha actualizado correctamente"
    end
  end

  def center_params
    params.require(:center).permit(:email, :phone, :second_phone, :description, :monday_friday, :saturday, :sunday)
  end

  def images
    if params[:images]
      center = Center.find(params[:center_id])
      params[:images].each do |image|
        CenterImage.create(photo: image, center: center)
      end
      redirect_to :back, notice: "Sus imágenes se añadieron correctamente"
    else
      redirect_to :back, alert: "No se seleccionó ninguna imagen o no pudo ser añadida"
    end
  end

  def delete_images
    @center = Center.find(params[:center_id])
    image = CenterImage.find(params[:image_id])
    if @center.present? and image.present?
      delete_image(image)
      @image_id = params[:image_id]
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render "fail_delete_image.js.erb" }
      end
    end
  end

  def center_admin
    @centers = current_user.centers
  end

  protected
  def delete_image(image)
    image.photo.destroy
    image.photo.clear
    image.delete
  end

  def admin_authenticate
    return false unless authenticate and (current_user.role.include? "admin" and owned_center_to_user?)
  end

  def owned_center_to_user?
    if !Center.exists?(id: params[:id])
      return false
    end
    redirect_to root_url, alert: "No tienes permisos" unless Center.find(params[:id]).user == current_user
  end
end

# def index
#   @articles = Article.con_titulo(params[:buscar])
#   if @articles.present?
#     respond_to do |format|
#       format.html
#       format.js
#     end
#   else
#     respond_to do |format|
#       format.html
#       format.js { render "fallo_articulos.js.erb" }
#     end
#   end
# end

app/helpers/centers_helper.rb
module CentersHelper
end

app/views/centers/_center.html.erb
<li>
  <%= div_for center do %>
      <h4>
        <%= link_to center.name, center %>
        <% for i in 1..center.rate.to_i do %>
            <i class="fa fa-1x fa-star hidden-xs"></i>
        <% end %>
      </h4>
      <% for i in 1..center.rate.to_i do %>
          <i class="fa fa-1x fa-star hidden-sm hidden-md hidden-lg"></i>
      <% end %>
      <div class="row">
        <% if center.center_images.count > 0 %>
            <%= image_tag center.center_images.first.photo.url(:medium), alt: "Center Image", class: "col-xs-2 center_main_image img-rounded" %>
        <% else %>
            <%= image_tag "default_center.jpg", alt: "Center Image", class: "small_image", class: "col-xs-2 center_main_image img-rounded"%>
        <% end %>
        <p class="col-xs-8"><%= center.description %></p>
      </div>
      <p><i class="fa fa-2x fa-map-marker"></i><strong> Direccion:</strong> <%= center.address %></p>
      <p><i class="fa fa-2x fa-phone"></i> <strong> Teléfono</strong>: <%= center.phone %></p>
      <h4><i class="fa fa-star"></i><%= link_to " Valorar", opinions_centers_path(id: center.id) %></h4>
  <% end %>
</li>

app/views/centers/_images_slider.html.erb
<% if @center.center_images.count > 0 %>
    <div id="myCarousel" class="carousel slide col-xs-12 col-md-10" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <% @center.center_images.each_with_index do |image, index| %>
            <% next unless index != 0 %>
            <li data-target="#myCarousel" data-slide-to="#{index}"></li>
        <% end %>
      </ol>

      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <%= image_tag @center.center_images.first.photo.url(:original), alt: "Center Image" %>
        </div>
        <% @center.center_images.each_with_index do |image, index| %>
            <% next unless index != 0 %>
            <div class="item">
              <%= image_tag image.photo.url(:original), alt: "Center Image" %>
            </div>
        <% end %>

      </div>
      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
<% end %>

app/views/centers/_map.html.erb
<script src="yourKey" async defer>
</script>
<script>
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: <%= @center.latitude %>, lng: <%= @center.longitude %>},
      zoom: 18
    });
  }
</script>

app/views/centers/_rate_modal.html.erb
<div class="modal fade" id="opinion_modal" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Completa el siguiente formulario</h4>
      </div>
      <div class="modal-body">
        <%= form_for([@center, @center.reviews.new]) do %>
            <div class="form-group">
              <label for="rate_title">Título:</label>
              <input name="title" type="text" class="form-control" id="rate_title" required>
            </div>
            <div>
              <h4>Instalaciones:</h4>
              <input name="infraestructure" type="number" class="rating" data-stars="5" min=0 max=5
                     step=0.5 data-size="xs" required>
              <hr>
              <h4>Actividades:</h4>
              <input name="activities" type="number" class="rating" data-stars="5" min=0 max=5
                     step=0.5 data-size="xs" required>
              <hr>
              <h4>Monitores:</h4>
              <input name="attention" type="number" class="rating" data-stars="5" min=0 max=5 step=0.5
                     data-size="xs" required>
              <hr>
              <h4>Limpieza:</h4>
              <input name="cleaning" type="number" class="rating" data-stars="5" min=0 max=5 step=0.5
                     data-size="xs" required>
              <hr>
              <h4>Vestuarios:</h4>
              <input name="bathroom" type="number" class="rating" data-stars="5" min=0 max=5
                     step=0.5 data-size="xs" required>
              <hr>
            </div>
            <div class="form-group">
              <p><label for="opinion">Opinión:</label></p>
              <textarea name="comment" class="form-control col-xs-10" rows="8" id="opinion" required></textarea>
            </div>
            <button type="submit" class="btn btn-default">Añadir reseña</button>
        <% end %>

      </div>
    </div>

  </div>
</div>

app/views/centers/_rating_area.html.erb
<div id="rating" class="col-xs-12 col-lg-10">
  <h3>Opiniones</h3>
  <% if @center.reviews.count > 0 %>
      <ul>
        <%= render @center.reviews %>
      </ul>
  <% else %>
      <p>¡Aún nadie ha elaborado ninguna reseña, sé el primero!</p>
  <% end %>
  <% if session[:username] %>
      <button class="btn btn-default" data-toggle="modal" data-target="#opinion_modal">Añadir reseña</button>
  <% else %>
      <button class="btn btn-default" data-toggle="modal" data-target="#loginModal">Iniciar sesión para añadir una
        reseña
      </button>
  <% end %>
  <br/>
  <br/>
</div>

app/views/centers/center_admin.html.erb
<div>
  <ul id="admin_center_list" class="col-xs-12 col-sm-6 col-sm-offset-1">
    <h3>Mis centros deportivos</h3>
    <% @centers.each do |center| %>
        <li>
          <% if center.center_images.count > 0 %>
              <%= image_tag center.center_images.first.photo.url(:thumb), alt: "Center Image" %>
          <% else %>
              <%= image_tag "default_center.jpg", alt: "Center Image", class: "small_image"%>
          <% end %>
          <%= link_to center.name, edit_center_path(id: center.id) %>
          <i class="fa fa-pencil"></i>
        </li>
    <% end %>
  </ul>
</div>

app/views/centers/delete_images.js.erb
$("#<%= j @image_id %>").remove();

app/views/centers/edit.html.erb
<% if @center.errors.any? %>
    <div class="alert alert-danger col-xs-8 col-xs-offset-2 hidden-sm col-md-3 hidden-md hidden-lg">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <h4>No hemos podido crear su centro, es necesario que corrija los siguientes errores:</h4>
      <ul id="new_user_errors">
        <% @center.errors.messages.values.each do |msg| %>
            <% msg.each do |m| %>
                <li><%= m %></li>
            <% end %>
        <% end %>
      </ul>
    </div>
<% end %>

<div id="sign_up_form" class="col-xs-8 col-xs-offset-2 col-sm-4 col-lg-3 col-sm-offset-2">
  <%= form_for @center, html: {multipart: true} do |f| %>
      <h3>Información general <i class="fa fa-info"></i></h3>

      <div class="field form-group">
        <%= f.label :phone, 'Teléfono' %></br>
        <%= f.text_field :phone, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :second_phone, 'Teléfono secundario' %></br>
        <%= f.text_field :second_phone, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :email, 'Email' %></br>
        <%= f.text_field :email, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :description, 'Descripción' %></br>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <h3>Horarios: </h3>

      <div class="field form-group">
        <%= f.label :monday_friday, 'Lunes a viernes' %></br>
        <%= f.text_field :monday_friday, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :saturday, 'Sábados' %></br>
        <%= f.text_field :saturday, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :sunday, 'Domingos' %></br>
        <%= f.text_field :sunday, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit 'Crear', :class => 'btn btn-default' %>
      </div>
      <br>

  <% end %>
</div>

<div id="sign_up_form" class="col-xs-8 col-xs-offset-2 col-sm-5 col-sm-offset-1 col-lg-4 col-lg-offset-1">
  <h3>Añadir imágenes <i class="fa fa-photo"></i></h3>
  <%= form_tag images_centers_path(center_id: @center), method: :post, multipart: true do %>
      <%= file_field_tag :images, multiple: true, name: "images[]", type: "file", required: true %>
      <br>
      <div class="actions">
        <%= submit_tag 'Añadir imágenes', :class => 'btn btn-default' %>
      </div>
  <% end %>
  <br><br>
</div>

<div id="sign_up_form" class="col-xs-8 col-xs-offset-2 col-sm-5 col-sm-offset-1 col-lg-4 col-lg-offset-1">
  <h3>Editar mis imágenes <i class="fa fa-photo"></i></h3>
  <ul id="delete_images">
    <% @center.center_images.each do |image| %>
        <li id="<%= image.id %>">
          <div>
            <%= image_tag image.photo.url(:thumb), alt: "Center Image" %>
            <%= link_to "Eliminar", delete_images_centers_path(image_id: image.id, center_id: @center.id), method: :post, remote: true %>
            <i class="fa fa-trash"></i>
          </div>
        </li>
        <br>
    <% end %>
  </ul>
</div>

app/views/centers/fail_search.js.erb
$("#centers_result").html("<p id='fail_search'><strong>Su búsqueda no produjo ningún resultado. Por favor, intentelo de nuevo...</strong></p>");
$("#centers_result").hide().slideDown();

app/views/centers/index.html.erb
<div class="col-xs-10" id="ajax_search">
  <%= form_tag centers_path, method: "get", role: "search", class: "col-xs-9 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-offset-2 col-md-6 col-lg-offset-1", remote: true do %>
      <p><strong>Buscar</strong></p>
      <div class="input-group">
        <%= text_field_tag :filter, params[:filter], class: "form-control", placeholder: "Centro deportivo, gimnasio, complejo" %>
        <div class="input-group-btn">
          <%= button_tag "Buscar", class: "btn btn-default", name: "" do %>
              <i class="glyphicon glyphicon-search"></i>
          <% end %>
        </div>
      </div>
  <% end %>
</div>
<h2 id="results_title" class="col-xs-9 col-xs-offset-1">Centros Deportivos</h2>
<div id="centers_result" class="col-xs-12 col-sm-10 col-md-8 col-md-offset-2 col-lg-offset-1">
  <% if @centers.count > 0 %>
      <ul>
        <%= render @centers %>
      </ul>
  <% else %>
      <p id='fail_search'>
        <strong>Su búsqueda no produjo ningún resultado. Por favor, intentelo de nuevo...</strong>
        <br>
        <br>
        <%= link_to "Búsqueda personalizada ", "/searchs", class: "btn btn-info" %>
      </p>
  <% end %>
</div>

app/views/centers/index.js.erb
$("#centers_result ").html("<ul><%= j render(@centers) %></ul>");
$("#centers_result ").hide().slideDown();

app/views/centers/opinions.html.erb
<div class="container-fluid">
  <div class="row">
    <div id="info" class="col-xs-11 col-xs-offset-1 col-sm-7 col-md-7 col-lg-7">
      <h1><%= link_to @center.name, @center %></h1>
    </div>
    <div id="ratin" class="col-xs-11 col-xs-offset-1 col-sm-7 col-md-7 col-lg-7">
      <%= form_for([@center, @center.reviews.new]) do %>
          <div>
            <div class="form-group">
              <label for="rate_title">Título:</label>
              <input name="title" type="text" class="form-control " id="rate_title" required>
            </div>
            <br>
            <h4>Instalaciones:</h4>
            <input name="infraestructure" type="number" class="rating" data-stars="5" min=0 max=5
                   step=0.5 data-size="md" required>
            <hr>
            <h4>Actividades:</h4>
            <input name="activities" type="number" class="rating" data-stars="5" min=0 max=5
                   step=0.5 data-size="md" required>
            <hr>
            <h4>Monitores:</h4>
            <input name="attention" type="number" class="rating" data-stars="5" min=0 max=5 step=0.5
                   data-size="md" required>
            <hr>
            <h4>Limpieza:</h4>
            <input name="cleaning" type="number" class="rating" data-stars="5" min=0 max=5 step=0.5
                   data-size="md" required>
            <hr>
            <h4>Vestuarios:</h4>
            <input name="bathroom" type="number" class="rating" data-stars="5" min=0 max=5
                   step=0.5 data-size="md" required>
            <hr>
          </div>
          <div class="form-group">
            <p><label for="opinion">Opinión:</label></p>
            <textarea name="comment" class="form-control col-xs-10" rows="8" id="opinion" required></textarea>
          </div>
          <% if session[:username] %>
              <button class="btn btn-default" data-toggle="modal" data-target="#opinion_modal">Añadir reseña</button>
          <% else %>
              <a class="btn btn-default" data-toggle="modal" data-target="#loginModal">Iniciar sesión para añadir
                una
                reseña
              </a>
          <% end %>
      <% end %>
    </div>
    <div id="info_right" class="col-xs-11 col-sm-3 col-md-4 col-lg-4" style="margin-top:-40px">
      <br><br><br>
      <a href="map"></a>
      <div id="map">
      </div>
      <div class="address">
        <h4>Parque de Las Rehoyas <i class="fa fa-2x fa-map-marker"></i></h4>
        <h4>Carretera Antigua del Norte, 35014</h4>
        <h4>Las Palmas de Gran Canaria</h4>
      </div>
      <h3>Valoración:</h3>
      <input id="only-stars" class="rating form-control hide" data-stars="5" value="<%= @center.rate %>"
             data-min="0" data-max="5" data-step="0.5" data-disabled="true" data-size="md">
    </div>
  </div>
</div>

<script>
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: <%= @center.latitude %>, lng: <%= @center.longitude %>},
      zoom: 18
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCQpC-fcG8nNR09V3luqk8ojQ8yw6g2gHc&callback=initMap" async defer></script>

app/views/centers/show.html.erb
<%= render "map" %>
<div class="container-fluid">
  <div class="row">
    <div id="info" class="col-xs-12 col-sm-9 col-md-8 col-lg-8">
      <h1><%= @center.name %></h1>

      <p id="only-starts">Estrellas RateFit: <input id="only-stars" class="rating form-control hide" data-stars="5"
                                                    value='<%= @center.get_media %>'
                                                    data-min="0" data-max="5" data-step="0.5" data-disabled="true"
                                                    data-size="xs">
      </p>

      <div id="description" class="col-xs-12 col-md-10 col-lg-10">
        <h4>Descripción</h4>

        <p>
          <%= @center.description %>
        </p>

        <div class="address hidden-sm hidden-md hidden-lg">
          <h3>Dirección</h3>

          <p><%= @center.address %><a href="#map"><i class="fa fa-2x fa-map-marker"></i></a>
          </p>
        </div>
        <div class="schedules hidden-sm hidden-md hidden-lg">
          <h3>Horarios <i class="fa fa-clock-o fa-2x"></i>
          </h3>
          <ul>
            <li>Lunes a Viernes: <%= @center.monday_friday %></li>
            <li>Sábados: <%= @center.saturday %></li>
            <li>Domingos: <%= @center.sunday %></li>
          </ul>
        </div>
      </div>

      <%= render "images_slider" %>

      <%= render "rating_area" %>
    </div>
    <div id="info_right" class="col-xs-12 col-sm-3 col-md-4 col-lg-3">
      <br/>
      <br/>
      <br/>
      <a href="map"></a>

      <div id="map">
      </div>
      <div class="address">
        <h3>Dirección <i class="fa fa-2x fa-map-marker"></i></h3>

        <p><%= @center.address %></p>
      </div>
      <div class="schedules hidden-xs">
        <h3>Horarios <i class="fa fa-clock-o"></i></h3>
        <ul>
          <li>Lunes a Viernes: <%= @center.monday_friday %></li>
          <li>Sábados: <%= @center.saturday %></li>
          <li>Domingos: <%= @center.sunday %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<% if session[:user_id] %>
    <%= render "rate_modal" %>
<% end %>



<% if flash[:review_error] %>
    <div class="modal fade" id="review_errors">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title">Se han encontrado los siguientes errores</h4>
          </div>
          <div class="modal-body">
            <div class="alert alert-danger">
              <ul id="new_user_errors">
                <% flash[:review_error].values.each do |msg| %>
                    <% msg.each do |m| %>
                        <li><%= m %></li>
                    <% end %>
                <% end %>
              </ul>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div>
    <script>
      $(document).ready(function () {
        $("#review_errors").modal("show");
      });
    </script>
<% end %>