config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get '/searchs/filter' => "searchs#filter"
  get "/searchs" => "searchs#index"
  post "/searchs/filter" => "searchs#filter", as: :search_filter

  resources :novelties, only: [:index] do
    collection do
      get 'betters'
    end
  end

  resources :centers do
    collection do
      get 'opinions'
      post "images"
      post "delete_images"
      get "admin"
      get "center_admin"
    end
    resources :reviews
  end

  resources :users
  resources :adverts

  resource :session, only: [:new, :create, :destroy]

  get '/logout' => "sessions#destroy", as: "logout"
  get '/notices/centers' => "notices#centers", as: "centers_info"
  get '/notices/trainners' => "notices#trainners", as: "trainners_info"

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def filter
    # @centers = Center.search_filter(params[:mun], (params[:price] or "low"), (params[:stars] or "0"), get_service(params[:aerobic]),
    #                                 get_service(params[:fitness]), get_service([:aquagym]), get_service(params[:tennis]),
    #                                 get_service(params[:zumba]))
    # @mun = params[:mun]
    # @price = params[:price]
    # @stars = params[:stars]
    # @fitness = params[:fitness]
    @centers = Center.search_filter(params[:mun], params[:price], params[:stars], get_service(params[:aerobic]),
                                    get_service(params[:fitness]), get_service(params[:aquagym]),
                                    get_service(params[:tennis]), get_service(params[:zumba]))
  end

  def get_service(service)
    if service
      return "1"
    end
    return ""
  end


end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/filter.html.erb
<%= render :file => "centers/index" %>

app/views/searchs/index.html.erb
<div class="container-fluid" id="custom_user_search">
  <%= form_tag users_path, method: :get do %>
      <h4 style="color: #ffa33f"><strong>Búsqueda de entrenadores</strong></h4>
      <div id="municipality_user" class="col-xs-10 col-lg-4">
        <label for="mun_user">Municipio</label>
        <select name="mun_user" class="form-control" id="mun_user">
          <option>Las Palmas de Gran Canaria</option>
          <option>Tejeda</option>
          <option>Telde</option>
          <option>Gáldar</option>
        </select>
        <br>
        <div class="actions col-xs-12">
          <%= submit_tag 'Buscar Entrenador', class: 'btn btn-default' %>
          <br><br>
        </div>
      </div>
  <% end %>
</div>
<br>
<div class="container-fluid" id="custom_center_search">
  <h4 class="col-xs-8" style="color: #ffa33f"><strong>Búsqueda especializada</strong></h4>
  <%= link_to "Buscar por nombre", centers_path, class: "btn btn-default", id:"name_search" %>
  <%= form_tag search_filter_path do %>
      <div id="municipality" class="col-xs-10 col-lg-4">
        <label for="mun">Municipio</label>
        <select name="mun" class="form-control" id="mun">
          <option>Las Palmas de Gran Canaria</option>
          <option>Tejeda</option>
          <option>Telde</option>
          <option>Gáldar</option>
        </select>
        <br>
      </div>
      <div class="clearfix visible-xs"></div>
      <div id="radio_search" class="col-xs-5 col-sm-2 col-lg-2">
        <strong>Precio</strong>
        <div class="radio">
          <label><%= radio_button_tag "price", "low" %>10-25€</label>
        </div>
        <div class="radio">
          <label><%= radio_button_tag "price", "medium" %>25-35€</label>
        </div>
        <div class="radio">
          <label><%= radio_button_tag "price", "high" %>35-50€</label>
        </div>
        <div class="radio">
          <label><%= radio_button_tag "price", "expensive" %>+50€</label>
        </div>
      </div>
      <div id="stars" class="col-xs-6 col-lg-2 col-sm-3">
        <strong>Valoración</strong>
        <div class="radio">
          <label><%= radio_button_tag "stars", "1" %>
            <i class="fa fa-star"></i>
          </label>
        </div>
        <div class="radio">
          <label><%= radio_button_tag "stars", "2" %>
            <i class="fa fa-star"></i><i class="fa fa-star"></i>
          </label>
        </div>
        <div class="radio">
          <label><%= radio_button_tag "stars", "3" %>
            <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
          </label>
        </div>
        <div class="radio">
          <label><%= radio_button_tag "stars", "4" %>
            <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
          </label>
        </div>
        <div class="radio">
          <label><%= radio_button_tag "stars", "5" %>
            <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
          </label>
        </div>
      </div>
      <div id="services" class="col-xs-12 col-sm-3 col-lg-2">
        <strong>Servicios</strong>
        <div class="checkbox">
          <label><%= check_box_tag "tennis", "tennis" %>
            Tennis
          </label>
        </div>
        <div class="checkbox">
          <label><%= check_box_tag "zumba", "zumba" %>
            Zumba
          </label>
        </div>
        <div class="checkbox">
          <label><%= check_box_tag "fitness", "fitness" %>
            Fitness
          </label>
        </div>
        <div class="checkbox">
          <label><%= check_box_tag "aquagym", "aquagym" %>
            Aquagym
          </label>
        </div>
        <div class="checkbox">
          <label><%= check_box_tag "aerobic", "aerobic" %>
            Aerobic
          </label>
        </div>
      </div>
      <div class="actions col-xs-12">
        <%= submit_tag 'Buscar Centro', class: 'btn btn-default' %>
        <br><br>
      </div>
  <% end %>
</div>

<script>
  $(document).ready(function () {
    $("#myNavbar ul li:nth-child(1)").addClass("active");
  });
</script>