config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get '/searchs/filter' => "searchs#filter"
  get "/searchs" => "searchs#index"
  post "/searchs/filter" => "searchs#filter", as: :search_filter

  resources :novelties, only: [:index] do
    collection do
      get 'betters'
    end
  end

  resources :centers do
    collection do
      get 'opinions'
      post "images"
      post "delete_images"
      get "admin"
      get "center_admin"
    end
    resources :reviews
  end

  resources :users
  resources :adverts

  resource :session, only: [:new, :create, :destroy]

  get '/logout' => "sessions#destroy", as: "logout"
  get '/notices/centers' => "notices#centers", as: "centers_info"
  get '/notices/trainners' => "notices#trainners", as: "trainners_info"

end

app/views/layouts/_footer.html.erb
<footer class="container-fluid">
  <div class="row">
    <p id="about_us" class="col-xs-12">Sobre nosotros</p>
  </div>
  <div class="row-fluid">
    <i class="fa fa-facebook fa-4x fa-pull-right"></i>
    <i class="fa fa-instagram fa-4x fa-pull-right"></i>
    <i class="fa fa-twitter fa-4x fa-pull-right"></i>
    <i class="fa fa-google-plus fa-4x fa-pull-right"></i>
  </div>

  <div class="row">
    <ul class="list-inline col-xs-10">
      <li><a href=""></a>Contactar</li>
      <li><a href=""></a>Historia</li>
      <li><a href=""></a>Aviso legal</li>
      <li><a href=""></a>Redes sociales</li>
    </ul>
  </div>
  <p id="copyright" class="pull-right">
    <i class="fa fa-copyright"></i> 2015 Rate Fitness
  </p>
</footer>

app/views/layouts/_navarea.html.erb
<div class="row">
  <%= link_to root_path, id: "slogan", class: "col-xs-7 col-sm-10 col-lg-10" do %>
      Believe in Fitness
  <% end %>
  <div id="users_area" class="col-sm-2 col-xs-4 col-lg-1">
    <div class="dropdown">
      <a href="users.html" class="dropdown-toggle" data-toggle="dropdown"><span
      class="glyphicon glyphicon-user"></span></a>
      <ul id="users_dropdown" class="dropdown-menu">
        <% if !session[:username] %>
            <li><a id="signin" href='#'>Iniciar sesión</a></li>
            <li><a id="signin" href='/users/new'>Registrarse</a></li>
        <% end %>
        <% if session[:username] %>
            <li><%= link_to "Editar perfil", edit_user_path(current_user) %></li>
            <% if current_user.role == "center_admin" %>
                <li><%= link_to "Mis centros", center_admin_centers_path %></li>
            <% end %>
            <li><a id="logout" href='/logout'>Salir</a></li>
        <% end %>
      </ul>
    </div>
    <p id="users_area_text">
      <% if session[:username] %>
          <%= session[:username] %>
      <% else %>
          <%= link_to "Usuarios", new_user_path %>
      <% end %>
    </p>

  </div>
</div>
<div class="row">
  <%= link_to root_path do %>
      <%= image_tag "logo.png", alt: "organization_logo", class: "pull-left hidden-xs hidden-sm col-md-1 img-rounded" %>
  <% end %>
  <nav id="nav" class="navbar navbar-inverse col-xs-12 col-sm-12 col-md-11 col-lg-11">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand hidden-sm hidden-md hidden-lg" href="index.html">RateFit</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class=""><%= link_to "Buscar", searchs_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Profesionales</a>
          <ul class="dropdown-menu">
            <li><%= link_to "Entrenadores personales", trainners_info_path %></li>
            <li><%= link_to "Centros deportivos", centers_info_path %></li>
          </ul>
        </li>
        <li><%= link_to "Escribir reseña", centers_path %></li>
        <li><%= link_to "Novedades", novelties_path %></li>
        <li><%= link_to "Mejor valorados", betters_novelties_path %></li>
      </ul>
    </div>
  </nav>
</div>
</div>
</div>

<div class="modal fade" id="loginModal" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <a type="button" class="close" data-dismiss="modal">&times;</a>
        <h4 class="modal-title">Inicia sesión o regístrate gratis para escribir una reseña</h4>
      </div>
      <div class="modal-body">
        <%= form_tag session_path do %>
            <div class="field form-group">
              <%= label_tag :username, 'Nombre de usuario' %></br>
              <%= text_field_tag :username, nil, class: 'form-control', required: true %>
            </div>
            <div class="field form-group">
              <%= label_tag :password %></br>
              <%= password_field_tag :password, nil, class: 'form-control', required: true %>
            </div>
            <div class="checkbox">
              <label><input type="checkbox"> Recordar</label>
            </div>
            <p><a href="recover_password">Olvidé mi cotnraseña</a></p>
            <% if flash[:login_error] %>
                <div class="alert alert-danger">
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                  <%= flash[:login_error] %>
                </div>
            <% end %>
            <div class="actions">
              <%= submit_tag 'Login', class: 'btn btn-default' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if flash[:login_error] %>
    <script>

      $(document).ready(function () {
        $("#loginModal").modal("show");
      });

    </script>
<% end %>

<div class="modal fade" id="info">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Información</h4>
      </div>
      <div class="modal-body">
        <% if flash[:notice] %>
            <div class="alert alert-info">
              <%= flash[:notice] %>
            </div>
        <% end %>
        <% if flash[:alert] %>
            <div class="alert alert-danger">
              <%= flash[:alert] %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if flash[:notice] or flash[:alert] %>
    <script type="text/javascript" charset="utf-8">
      $(document).ready(function () {
        $("#info").modal("show");
      });
    </script>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="row">
  <a id="slogan" class="col-xs-7 col-sm-10 col-lg-11">Believe in Fitness</a>

  <div id="users_area" class="col-xs-1 col-sm-1">
    <div class="dropdown">
      <a href="users.html" class="dropdown-toggle" data-toggle="dropdown"><span
      class="glyphicon glyphicon-user"></span></a>
      <ul id="users_dropdown" class="dropdown-menu">
        <li><a id="signin" href='#'>Iniciar sesión</a></li>
        <li><a id="edit_profile" href='#'>Editar Perfil</a></li>
        <li><a id="logout" href='#'>Salir</a></li>
      </ul>
    </div>
    <span id="users_area_text"><a href="users.html">usuarios</a></span>
  </div>
  <a href="index.html">
    <%= image_tag "logo.png", alt: "organization_logo", class: "hidden-xs col-sm-1 img-rounded" %>
  </a>
  <nav id="nav" class="navbar navbar-inverse col-xs-12 col-sm-10 col-lg-11">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand hidden-sm hidden-md hidden-lg" href="index.html">RateFit</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#"> Buscar</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Profesionales</a>
          <ul class="dropdown-menu">
            <li><a href="#">Entrenadores personales</a></li>
            <li><a href="#">Centros deportivos</a></li>
          </ul>
        </li>
        <li><a href="#"> Escribir reseña</a></li>
        <li><a href="#"> Novedades</a></li>
        <li><a href="#">Mejor valorados</a></li>
      </ul>
    </div>
  </nav>
</div>
</div>

app/views/layouts/_register.html.erb
<script>
  $(document).ready(function () {
    registUserAreaEvents();

    if (localStorage.getItem("login")) {
      changeUserContext();
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>RateFit</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <%= render "layouts/navarea", :layout => true %>
  <%= yield %>
  <%= render "layouts/footer" %>
  <%= render "layouts/register" %>
</div>
</body>
</html>